# The following attributes can be modified to better control how the application works.
# However, there is no mandatory key-value pair to define, thus requiring no effort from the user to make use of the program immediately after installation

[paths]
#path_xhb = 
#path_excel =

[mappings]